### ISSUE TITLE
Out of order - Curriculum issues

### ISSUE THREAD

**Issue by ScottDenton** [learn-co-curriculum/prototypal-oo-js-using-prototypes#3]
This lab explaining how and when to use prototypes comes after 2 labs that required we use them. The lab explaining a new concept should be before the lab asking you to use that concept. 
I would suggest moving this before the two previous labs in the order.

**Comment by maxwellbenton** [comment]
Hi @ScottDenton,

Thank you for spotting this and providing feedback. This section was incorrectly organized when the module track was built. We've reordered this content, removed a duplicate lesson and added in a  lesson that had not been added.

Thank you for participating in testing this curriculum content and for helping to improve it for future students! 💙
